services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - /etc/ssl:/etc/ssl:ro
      - /var/log/nginx:/var/log/nginx
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
      - 0.0.0.0:8070:8070
    healthcheck:
      test: [ "CMD-SHELL", "service nginx status || exit 1" ]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge